// <auto-generated />
namespace Lab_Example.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.4.4")]
    public sealed partial class FullProducts : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(FullProducts));
        
        string IMigrationMetadata.Id
        {
            get { return "202201250955295_FullProducts"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
